### ISSUE TITLE
tutorial of edgedf.csv and ggtree

### ISSUE THREAD

**Issue by grimwoo** [XingyanLiu/stagewiseNN#2]
hi , thanks for the development of stagewiseNN.

Using the provided "subsampled_B-L0-0.2.h5ad" and the detailed tutorial, I successfully got the "edgedf.csv" file.
Could I know the following tutorial to plot the tree in ggtree with the "edgedf.csv" ?

![image](https://user-images.githubusercontent.com/49429496/176117691-4ad35459-37c2-41f2-8db0-d01788aa59c7.png)

**Comment by XingyanLiu** [comment]
The developmental tree is plotted by the R package 'ggtree' (https://github.com/YuLab-SMU/ggtree). The codes/tutorial for plotting the figures in the CR paper will be complemented later this week.

**Comment by grimwoo** [comment]
@XingyanLiu Thank you for your quick reply and look forward to your code this week~

**Comment by XingyanLiu** [comment]
The function for visualizing the developmental tree can be found at https://github.com/XingyanLiu/AmphioxusAnalysis

<img width="620" alt="image" src="https://user-images.githubusercontent.com/23734945/177047728-d4233f85-c75f-4345-bc41-50371ed35ffe.png">

**Comment by grimwoo** [comment]
@XingyanLiu Thank you so much
